This content is produced and maintained by the Eclipse Dash, Tools for
Committers project.

* Project home: http://jnosql.org/

== Declared Project Licenses

This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is
 available at https://www.eclipse.org/legal/epl-2.0, or the Apache Software License 2.0 which is available 
 at https://www.apache.org/licenses/LICENSE-2.0.


== Source Code

* https://github.com/eclipse/jnosql.git

== Copyright Holders

Copyright 2016-2017 The Eclipse Foundation

== Third-party Content

JUniT Version: 4.12
* License: Eclipse Public License, 2.0


== Cryptography

Content may contain encryption software. The country in which you are currently
may have restrictions on the import, possession, and use, and/or re-export to
another country, of encryption software. BEFORE using any encryption software,
please check the country's laws, regulations and policies concerning the import,
possession, or use, and re-export of encryption software, to see if this is
permitted.